# Generated by Django 3.0.14 on 2022-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollers',
            fields=[
                ('id_enrollers', models.AutoField(primary_key=True, serialize=False, verbose_name='id_enrollers')),
                ('image_enrollers', models.ImageField(blank=True, null=True, upload_to='media/Images_enrollers/%y', verbose_name='image_enrollers')),
                ('rut_enrollers', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id_markers', models.AutoField(primary_key=True, serialize=False, verbose_name='id_marker')),
                ('image_markers', models.ImageField(blank=True, null=True, upload_to='media/Images_markers/%y', verbose_name='image_markers')),
                ('rut_markers', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
