# Generated by Django 3.0.14 on 2022-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAPTURERS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False, verbose_name='id_dispositivo')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('machine', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('release', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
