# Generated by Django 3.0.14 on 2022-08-16 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAPTURERS', '0002_dispositivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='fecha_markers',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
