# Generated by Django 3.0.14 on 2022-08-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CAPTURERS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id_register', models.AutoField(primary_key=True, serialize=False, verbose_name='id_register')),
                ('names', models.CharField(blank=True, max_length=100, null=True)),
                ('surnames', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('rut_enrollers', models.ForeignKey(db_column='rut_enrolado', on_delete=django.db.models.deletion.CASCADE, to='CAPTURERS.Enrollers')),
            ],
        ),
    ]
